### ISSUE TITLE
Polish translating

### ISSUE THREAD

**Issue by 0xtrzy** [ellbrid/krabs#14]
Is possible add localisation (multilanguage) version krabs?
Trouble is with different chars or graphics

**Comment by ellbrid** [comment]
Krabs will only support the Standard character set for each code page. Therefore, there is currently no plan to support the Extended character set. For Polish printing, is it the [cp852](https://www.ascii-codes.com/cp852.html)'s Extended char set? Unfortunately, there are no plans to make this available.
Are you experiencing any serious issues, such as Krabs not starting?

**Comment by ellbrid** [comment]
No response, close once. Please reopen this issue if you still have any concerns.
